name: Databricks CD with AAD Token

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/cd-aad.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
          
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
      - id: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-url: 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d
      
      - name: generate-databricks-token
        run: | 
          echo  ${{ steps.azure-resource-login.outputs.resourceToken }}
          echo "DATABRICKS_TOKEN= ${{ steps.azure-resource-login.outputs.resourceToken }}" >> $GITHUB_ENV
            
      - name: Import Databricks notebooks
        uses: ./
        with:
          databricks-host: ${{ secrets.ADB_HOST }}
          databricks-token: ${{ env.DATABRICKS_TOKEN }}
          local-path: ./notebooks
          remote-path: /import-notebook
