name: Databricks CD

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
          
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
